### Site metadata ###

title: Code Cookbook
description: Reusable code patterns which you can use as reference or copy to your project

github_username: MichaelCurrin

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/code-cookbook"

google_analytics: G-ED9PSVN5DS

header_pages:
  - index.md
  - recipes/index.md
  - about.md

exclude:
  - bin/
  - docs/
  - hooks/
  - vendor/
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

### Theme boilerplate ###

remote_theme: MichaelCurrin/fractal

titles_from_headings:
  strip_title: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
