name: Check markdown links

on: push

# See
# https://github.com/MichaelCurrin/code-cookbook/tree/master/recipes/ci-cd/github-actions/workflows/check-links

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

  link-checker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r recipes
      
    - name: Fail on link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
      
