name: Check markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

jobs:
  link-checker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      
