name: Check markdown links

# Disabled on master push as this has false positives which is noisy. Plus there is the cost of running.
on: pull_request

# See
# https://github.com/MichaelCurrin/code-cookbook/tree/master/recipes/ci-cd/github-actions/workflows/check-links

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
